---
sudo: false
language: ruby
cache: bundler
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
#- bundle exec rake $CHECK
matrix:
  fast_finish: true
  include:
  - rvm: 2.2.5
    env: PUPPET_GEM_VERSION="~> 3.5.0" STRICT_VARIABLES="yes"
notifications:
  email: false
#deploy:
#  provider: puppetforge
#  user: dhoppe
#  password:
#    secure: "DwZQehUuDCVCjj/7a82Bj6at+JXcF5b6Rl7impaFnia9QgvEPvdt72cxX04SkPfLM99wy/x3RPqHeEfyoPMHoR9SpUKnFWFChumkW794qpWFCweG18vOr9P+E6PGUp3xRXHar7Yv1BGg/pdEajq+s97NQJn42pkhanl6v8JD5MI="
#  on:
#    tags: true
    # all_branches is required to use tags
#    all_branches: true
    # Only publish if our main Ruby target builds
#    rvm: 1.9.3
